### ISSUE TITLE
在OPPO PBAT00 出现了问题

### ISSUE THREAD

**Issue by tao111222333444** [wildma/IDCardCamera#10]
![image](https://user-images.githubusercontent.com/12760236/51665030-cd1a1d00-1ff5-11e9-99ab-885502b31f07.png)

**Comment by wildma** [comment]
@tao111222333444 你好，请提供详细的报错信息或者说下复现步骤，方便我这边排查~

**Comment by tao111222333444** [comment]
拍照完成后点击  确认（绿色的勾）就会崩掉

**Comment by tao111222333444** [comment]
@wildma 拍照完成后点击 确认（绿色的勾）就会崩掉

**Comment by tao111222333444** [comment]
@wildma 
![image](https://user-images.githubusercontent.com/12760236/53849066-9f12fa00-3ff1-11e9-9a27-c2515dfe9bcc.png)

**Comment by wildma** [comment]
@tao111222333444 上传了最新代码，由于我这边没有该机型的手机，所以麻烦你下载最新代码（直接下载最新代码，不要用依赖的）测试一下是否解决。

**Comment by moon2009** [comment]
我使用您的最新代码在oppo A83也有这个错误
java.lang.RuntimeException: Camera is being used after Camera.release() was called
    at android.hardware.Camera.setHasPreviewCallback(Native Method)
    at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:1030)
    at com.wildma.idcardcamera.camera.CameraActivity.d(CameraActivity.java:238)
    at com.wildma.idcardcamera.camera.CameraActivity.onClick(CameraActivity.java:218)

对应代码
 else if (id == R.id.iv_camera_take) {
            takePhoto();
        }

  /**
     * 拍照
     */
    private void takePhoto() {
        mCameraPreview.setEnabled(false);
        CameraUtils.getCamera().setOneShotPreviewCallback(new Camera.PreviewCallback() {
     、、、、
   }

**Comment by wildma** [comment]
@moon2009 由于我这边没有该机型的手机，复现不出该问题，如果你那边能解决欢迎PR。

**Comment by LuckyBing** [comment]
点勾会崩溃
