### ISSUE TITLE
拍正面照时内存泄漏

### ISSUE THREAD

**Issue by hcy940215** [wildma/IDCardCamera#14]
拍正面照时内存泄漏

**Comment by wildma** [comment]
demo 中已经加入了 leakCanary 来检测内存泄漏，由于我这边没有检测出来，麻烦提供下 demo 中导致内存泄漏的操作步骤和内些泄漏后 leakCanary 检测出来的信息，方便我这边排查，谢谢。

**Comment by hcy940215** [comment]
操作步骤：下载您的工程，运行Demo，身份证正面-拍照，Leaks 就会打印出信息。以下为截图
[CameraActivity 信息](https://imgchr.com/i/VZR3Gj)

**Comment by hcy940215** [comment]
操作步骤：下载您的工程，运行Demo，身份证正面-拍照，Leaks 就会打印出信息。以下为截图
![CameraActivity 信息](https://s2.ax1x.com/2019/05/27/VZR3Gj.png)

**Comment by wildma** [comment]
目前我这边复现不了，后面有时间我换其他手机试试。

**Comment by shushenc871129** [comment]
大佬，demo拍正面照会提示"Dumping memory, app will freeze Brrr"

**Comment by shushenc871129** [comment]
上面报内存泄漏用的是华为平板M3青春版10，刚刚又用手机红米note7 pro试了下，这款手机没有问题

**Comment by wildma** [comment]
@shushenc871129 目前试了手上的几个手机还是复现不了，如果你那边能解决欢迎 PR。
