### ISSUE TITLE
拍照后，点击绿色对号没有反应

### ISSUE THREAD

**Issue by ArthurTom** [wildma/IDCardCamera#17]
拍照后，点击对号，没有反应。 拍摄身份证正面的时候出现，小米，华为。oppo等机型。
有时可以 点击，有时候无法反应。

**Comment by wildma** [comment]
“有时可以 点击，有时候无法反应。”，你这个反应很诡异呀，我这边复现不了，你可以在点击事件那里断点排查下具体问题。
