### ISSUE TITLE
拍照回来之后页面的数据被重置了

### ISSUE THREAD

**Issue by BoBoJiangs** [wildma/IDCardCamera#27]
华为P20 系统版本 8.1.0

**Comment by BoBoJiangs** [comment]
https://blog.csdn.net/s13488941815/article/details/102852117 我采用这种方式暂时解决了

**Comment by wildma** [comment]
经验证，在 Demo 中的 MainActivity 页面增加 EditText，输入文字后进行拍照，拍照返回并没有重置页面数据。并不太了解你遇到的问题。

**Comment by wangchengcheng1992** [comment]
身份证正面拍照成功后，再进行修改，再次正面拍照，返回之后图片展示没有改变。问题机型：华为mate20 系统版本9.1.0

**Comment by BoBoJiangs** [comment]
@wildma 跟机型有关系 因为拍照哪个页面是横批的 部分手机拍完照回来之后 页面会进行一次横竖屏切换导致的

**Comment by wildma** [comment]
@BoBoJiangs 嗯，可能是部分手机才会出现，目前我这边没有该机型无法复现，如果你那边能解决欢迎 PR。
