### ISSUE TITLE
身份证正面拍照成功后，再进行修改，再次正面拍照，返回之后图片展示没有改变。问题机型：华为mate20 系统版本9.1.0

### ISSUE THREAD

**Issue by wangchengcheng1992** [wildma/IDCardCamera#29]
身份证正面拍照成功后，再进行修改，再次正面拍照，返回之后图片展示没有改变。问题机型：华为mate20 系统版本9.1.0

**Comment by wildma** [comment]
Demo 没有这个问题。第二次返回之后图片展示没有改变可能是第二次出现了异常？可以看看是什么引起的。
