### ISSUE TITLE
对焦代码经常崩溃。

### ISSUE THREAD

**Issue by LoveRain1997** [wildma/IDCardCamera#3]
#2302 java.lang.RuntimeException
autoFocus failed

com.wildma.idcardcamera.camera.CameraPreview.focus(CameraPreview.java:169)

android.hardware.Camera.native_autoFocus(Native Method)
--
2 android.hardware.Camera.autoFocus(Camera.java:1164)
3 com.wildma.idcardcamera.camera.CameraPreview.focus(CameraPreview.java:169)
4 com.wildma.idcardcamera.camera.CameraPreview$1.onFocus(CameraPreview.java:59)
5 com.wildma.idcardcamera.camera.SensorControler.onSensorChanged(SensorControler.java:115)
6 android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:804)
7 android.os.MessageQueue.nativePollOnce(Native Method)
8 android.os.MessageQueue.next(MessageQueue.java:138)
9 android.os.Looper.loop(Looper.java:123)
10 android.app.ActivityThread.main(ActivityThread.java:5143)
11 java.lang.reflect.Method.invokeNative(Native Method)
12 java.lang.reflect.Method.invoke(Method.java:515)
13 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
14 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
15 dalvik.system.NativeStart.main(Native Method)

**Comment by LoveRain1997** [comment]
建议try下

**Comment by wildma** [comment]
@LoveRain1997 感谢建议，已改进。
