### ISSUE TITLE
旋转屏幕时可能崩溃

### ISSUE THREAD

**Issue by LoveRain1997** [wildma/IDCardCamera#4]
log：
#1804 android.content.res.Resources$NotFoundException
Resource ID #0x7f0b0020
com.wildma.idcardcamera.camera.CameraActivity.init(CameraActivity.java:131)

Activity配置下android:configChanges="orientation"

**Comment by wildma** [comment]
@LoveRain1997 之前已经改了，目前最新的版本已发布。
