### ISSUE TITLE
裁剪崩溃

### ISSUE THREAD

**Issue by LoveRain1997** [wildma/IDCardCamera#6]
# main(1)

java.lang.IllegalArgumentException

height must be > 0
1 android.graphics.Bitmap.checkWidthHeight(Bitmap.java:572)
--
2 android.graphics.Bitmap.createBitmap(Bitmap.java:928)
3 android.graphics.Bitmap.createBitmap(Bitmap.java:896)
4 com.wildma.idcardcamera.cropper.CropOverlayView.crop(CropOverlayView.java:373)
5 com.wildma.idcardcamera.cropper.CropImageView.crop(CropImageView.java:53)
6 com.wildma.idcardcamera.camera.CameraActivity.confirm(CameraActivity.java:280)
7 com.wildma.idcardcamera.camera.CameraActivity.onClick(CameraActivity.java:195)

**Comment by wildma** [comment]
那是因为你裁剪的高=0了，目前为了用户体验已改进。

**Comment by wildma** [comment]
@LoveRain1997 那是因为你裁剪的高=0了，目前为了用户体验已改进。
