### ISSUE TITLE
自动裁剪有bug

### ISSUE THREAD

**Issue by daqindiguo** [wildma/IDCardCamera#8]
#1402 java.lang.IllegalArgumentException
x + width must be <= bitmap.width()
com.wildma.idcardcamera.camera.CameraActivity
 /*自动裁剪*/
                        mCropBitmap = Bitmap.createBitmap(bitmap,
                                (int) (left * (float) bitmap.getWidth()),
                                (int) (top * (float) bitmap.getHeight()),
                                (int) ((right - left) * (float) bitmap.getWidth()),
                                (int) ((bottom - top) * (float) bitmap.getHeight()));
在OPPO PBEM00手机上会闪退

**Comment by wildma** [comment]
这手机是全面屏带刘海或者水滴屏的吗？

**Comment by wildma** [comment]
@daqindiguo 这手机是全面屏带刘海或者水滴屏的吗？

**Comment by shenliangshanghai** [comment]
部分全面屏确实有这个bug,裁剪的尺寸大于bitmap尺寸了

**Comment by wildma** [comment]
@shenliangshanghai @daqindiguo 问题已解决，请使用最新版本。
